"use client";

import { Plus } from "lucide-react";

export type AISuggestionSource = "doc" | "ki";

export interface AISuggestionItemProps {
  text: string;
  category?: string | null;
  /**
   * "doc"  — retrieved from project documentation (RAG)
   * "ki"   — generated by the AI model (LLM)
   * Omit to hide the source pill entirely.
   */
  source?: AISuggestionSource;
  onAdd: () => void;
}

const SOURCE_STYLES: Record<AISuggestionSource, { label: string; cls: string }> = {
  doc: {
    label: "Doc",
    cls: "text-[#526b5e] bg-[rgba(82,107,94,.08)] border-[rgba(82,107,94,.3)]",
  },
  ki: {
    label: "KI",
    cls: "text-[#a09080] bg-[rgba(160,144,128,.07)] border-[#e2ddd4]",
  },
};

/**
 * Single AI suggestion entry.
 *
 * Shared between DefinitionOfDoneSection (DoD context) and AISuggestPanel
 * (story improvement context). Both cases need a category badge, optional
 * source pill, suggestion text, and a compact add button.
 */
export function AISuggestionItem({ text, category, source, onAdd }: AISuggestionItemProps) {
  const sourceMeta = source ? SOURCE_STYLES[source] : null;

  return (
    <div className="relative flex items-start gap-2 px-3 py-2.5 border border-[#e2ddd4] rounded-sm bg-[#faf9f6] hover:border-[rgba(139,94,82,.3)] transition-colors group">
      <div className="flex-1 min-w-0">
        {(category || sourceMeta) && (
          <div className="flex items-center gap-1.5 mb-1">
            {category && (
              <span className="shrink-0 px-1.5 py-0.5 bg-[rgba(139,94,82,.08)] text-[#8b5e52] rounded-sm text-[7px] font-medium uppercase tracking-[.06em] [font-family:var(--font-mono)]">
                {category}
              </span>
            )}
            {sourceMeta && (
              <span
                className={`inline-flex items-center gap-1 shrink-0 px-1.5 py-px rounded-[10px] border-[0.5px] text-[6px] font-medium uppercase tracking-[.08em] [font-family:var(--font-mono)] ${sourceMeta.cls}`}
              >
                <span className="w-[5px] h-[5px] rounded-full bg-current inline-block shrink-0" />
                {sourceMeta.label}
              </span>
            )}
          </div>
        )}
        <span className="text-sm text-[#5a5040] break-words leading-snug">{text}</span>
      </div>

      {/* Plus button — top-right corner, revealed on hover */}
      <button
        type="button"
        onClick={onAdd}
        aria-label="Vorschlag übernehmen"
        className="absolute top-[6px] right-[6px] w-[18px] h-[18px] flex items-center justify-center bg-[rgba(139,94,82,.08)] border-[0.5px] border-[rgba(139,94,82,.3)] text-[#8b5e52] rounded-sm opacity-0 group-hover:opacity-100 transition-all hover:bg-[#8b5e52] hover:text-white"
      >
        <Plus size={10} />
      </button>
    </div>
  );
}
